FROM php:8.4-fpm

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    nginx

# Установка PHP расширений
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Nginx конфигурация
COPY docker/nginx.conf /etc/nginx/sites-available/default

# Копируем проект
WORKDIR /var/www/backend

# Устанавливаем права
RUN chown -R www-data:www-data /var/www/backend

# Запускаем Nginx и PHP-FPM
CMD service nginx start && php-fpm